# Generated by Django 3.1.7 on 2021-03-20 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteMovies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=168, null=True, verbose_name='Nome do Filme:')),
                ('watchedDate', models.DateField(blank=True, null=True, verbose_name='Data que assistiu (DD/MM/YY):')),
                ('rating', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], null=True, verbose_name='Nota para o filme (0-10):')),
            ],
            options={
                'db_table': 'FMovies',
            },
        ),
    ]
